services:
  - type: web
    name: nacionmx-bot
    runtime: node
    plan: free
    buildCommand: npm install --prefix bot
    startCommand: node bot/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DISCORD_TOKEN
        value: MTQ1MDcwMTYxNzY4NTk5MTYyMQ.Gwwg5B.YM9kFRCu6c2iqxbKAc8lIZw0wxXeC6QlfeBSB0
      - key: GUILD_ID
        value: "1398525215134318713"
      - key: NOTIFICATION_CHANNEL_ID
        value: "1450343644652507136"
      - key: SUPABASE_SERVICE_ROLE_KEY
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlnamVkd2R4cXdrcGJncm10cnJxIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2NTczNDEyNCwiZXhwIjoyMDgxMzEwMTI0fQ.DI4Sp6dQu4KVrK525a-VWcdmWx0KQg_MfMrTnjP8pLA
      - key: SUPABASE_URL
        value: https://igjedwdxqwkpbgrmtrrq.supabase.co
      - key: UNBELIEVABOAT_TOKEN
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcHBfaWQiOiIxNDUwNzAyNjY0OTI0MDA2MjE4IiwiaWF0IjoxNzY1OTQ0ODY4fQ.XqHP2mRU_eVVQeVfA-uajBOakYGYFr_vFNYr4-WrJOg
      - key: VITE_DISCORD_CLIENT_ID
        value: "1450701617685991621"
